### ISSUE TITLE
Background color behind screensharing

### ISSUE THREAD

**Issue by ericbieller** [speak/guest#109]
Currently if you toggle on and off it shows up as transparent which feels weird. Also, should we force the cog to stay on their user block?

**Comment by tommoor** [comment]
I think we should not let them click on their own screen actually, as you get the weird ghosting effect

**Comment by ericbieller** [comment]
I would agree, so we wouldn't show the screenshare box at the bottom at all when you're screensharing?

**Comment by tommoor** [comment]
We can show it, just you wouldn't be able to focus it in the center when it's yours... having the mini preview to remind you of what's being shared definitely worth while

**Comment by ericbieller** [comment]
Gotcha, in that case it doesn't really address the problem. It's that when you enable screenshare, it's transparent for a second so the cog appears to be hovering on nothing. Just looks a tad glitchy.

**Comment by tommoor** [comment]
:+1:
