### ISSUE TITLE
Update channel with meeting name

### ISSUE THREAD

**Issue by tommoor** [speak/guest#19]
If a meeting name is submitted as part of authentication then update the relevant channel with that name

**Comment by ericbieller** [comment]
What do we want to show in place of the name if one isn't supplied?

**Comment by tommoor** [comment]
does it look bad with just the time?

**Comment by ericbieller** [comment]
Haven't messed with it, but figured we'd want something there so they can still have the pencil icon to change the name?

**Comment by tommoor** [comment]
Yes I suppose, a placeholder "Name this call" or equivalent
