### ISSUE TITLE
Implementation of post meeting message

### ISSUE THREAD

**Issue by tommoor** [speak/guest#20]
When the last person leaves show a message and cta
- [x] Logic to show message
- [x] Delay a few seconds before displaying (the user may fall offline briefly)
- [ ] CSS

**Comment by ericbieller** [comment]
We discusses tailoring this message to call specifics like length / participant count. Have you thought much more about the specifics or language we might use?

**Comment by tommoor** [comment]
Not really, I think we should keep it simple in a first pass I guess... done this for now:

![image](https://cloud.githubusercontent.com/assets/380914/10985920/2e991c7c-83da-11e5-89a3-b0010c5fd4c8.png)

thoughts?

**Comment by ericbieller** [comment]
Yep fine for now, custom will definitely be a level above though!
