### ISSUE TITLE
Default avatars

### ISSUE THREAD

**Issue by ericbieller** [speak/guest#44]
They're not looking so good anymore. Here's a wild idea. Cute kitties!

![guest call 2x](https://cloud.githubusercontent.com/assets/740552/10983716/d969cecc-83d9-11e5-9e40-714e375e68e6.png)

**Comment by tommoor** [comment]
Lets see some other options :tongue:

**Comment by awsmsrc** [comment]
yeah not the biggest fan, only because its not that clear they are placeholders.
