### ISSUE TITLE
Incompatible browser screen

### ISSUE THREAD

**Issue by tommoor** [speak/guest#52]
- [x] Implementation
- [ ] Styling

**Comment by tommoor** [comment]
@ericbieller want to make the equivalent logo for safari? 

![image](https://cloud.githubusercontent.com/assets/380914/11051528/e362eb42-8704-11e5-843c-7eabda4fd7d0.png)

**Comment by ericbieller** [comment]
![incompatible-edge 2x](https://cloud.githubusercontent.com/assets/740552/11072858/821c1e18-87ad-11e5-9eb6-56dbcc46e5e7.png)
![incompatible-safari 2x](https://cloud.githubusercontent.com/assets/740552/11072879/9618f634-87ad-11e5-961c-78b6c9d66774.png)
