### ISSUE TITLE
Add record button to call controls

### ISSUE THREAD

**Issue by tommoor** [speak/guest#54]
- Record button in call controls should show a dialog that says paid accounts coming soon
- Track even in keen

**Comment by tommoor** [comment]
Any thoughts you have on a 'whoa, we're still working on this give us your email' kind of screen would be good

**Comment by ericbieller** [comment]
Could do app takeover like this. Also, if we already have their email we could hide the field.

![avatars v2 2x copy 2](https://cloud.githubusercontent.com/assets/740552/11042868/4e9315fc-86df-11e5-8a54-75ac4b3a2296.png)

![avatars v2 2x](https://cloud.githubusercontent.com/assets/740552/11042917/9b4395f2-86df-11e5-861d-248cd96b5ed2.png)

**Comment by tommoor** [comment]
Nice and simple, I can implement this pretty quickly. Is this a style we could use for the other modals - add people, settings etc? Probably.

**Comment by ericbieller** [comment]
@tommoor I think so yeah
