### ISSUE TITLE
Leave button

### ISSUE THREAD

**Issue by tommoor** [speak/guest#59]
What do we want this to do? As this needs to be quite clear that you have 'left' the call and are no longer broadcasting we might need to be able to send them to the 'start a meeting' screen whilst signed in.

**Comment by ericbieller** [comment]
I'd say send them to the 'start a meeting' screen, maybe even with a message "You've left" or summit.

**Comment by tommoor** [comment]
Assigned to myself, need to make it possible to be on that screen whilst signed in.
