### ISSUE TITLE
Finish styling channel name

### ISSUE THREAD

**Issue by tommoor** [speak/guest#68]
@ericbieller what do you think of this in the top left? Loving? Hating? If you think it's okay then it needs finishing up with an icon that indicates it's editable and probably a better placeholder text than 'subject' - I've been struggling to think of something...

**Comment by ericbieller** [comment]
Been mocking it up in the top left, don't hate it. Are we thinking the owner can name it or anything? Maybe another perk of upgrading? 

Here are some ideas for default:
- "Untitled" similar to google docs, a bit boring.
- "Name this room" prompting them to name it, but then we have to call it something.. room, meeting, etc..
- Give it a fun name, similar to appear, etc.. Could do a theme like "Green Forest", "Blue Lake", "Golden Desert"

![image](https://cloud.githubusercontent.com/assets/740552/11049146/f4814ade-8701-11e5-98ba-28c56507c04a.png)
