### ISSUE TITLE
Auto-link urls in the chat

### ISSUE THREAD

**Issue by tommoor** [speak/guest#69]
Seems like a bit of a no-brainer, probably one of the main things it would get used for

**Comment by willbarrett** [comment]
In Sqwiggle, we detected links on the back-end and treated them as attachments. Do we want to handle it the same way, or simply wrap it in an 'a' tag on the front end?

**Comment by tommoor** [comment]
Lets simply wrap in the display for now, just want to make them clickable, maybe remove http(s):// from the displayed version?

Twitter has an excellent library for this
